load("@bazel_skylib//rules:common_settings.bzl", "bool_setting")
load("@rules_license//rules:license.bzl", "license")
load("@rules_license//rules:license_kind.bzl", "license_kind")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        ":SPDX-license-identifier-Apache-2.0",
    ],
    license_text = "LICENSE-APACHE",
    visibility = [":__subpackages__"],
)

license_kind(
    name = "SPDX-license-identifier-Apache-2.0",
    conditions = ["notice"],
    url = "https://spdx.org/licenses/Apache-2.0.html",
)

bool_setting(
    name = "aemu_build_tests",
    build_setting_default = False,
)

config_setting(
    name = "aemu_tests_enabled",
    flag_values = {
        ":aemu_build_tests": "1",
    },
)

config_setting(
    name = "aemu_tests_disabled",
    flag_values = {
        ":aemu_build_tests": "0",
    },
)

bool_setting(
    name = "aemu_use_absl",
    build_setting_default = False,
)

config_setting(
    name = "aemu_absl_enabled",
    flag_values = {
        ":aemu_use_absl": "1",
    },
)

config_setting(
    name = "aemu_absl_disabled",
    flag_values = {
        ":aemu_use_absl": "0",
    },
)

bool_setting(
    name = "aemu_use_lz4",
    build_setting_default = False,
)

config_setting(
    name = "aemu_lz4_enabled",
    flag_values = {
        ":aemu_use_lz4": "1",
    },
)

config_setting(
    name = "aemu_lz4_disabled",
    flag_values = {
        ":aemu_use_lz4": "0",
    },
)
