load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "aemu-snapshot",
    srcs = [
        "TextureLoader.cpp",
        "TextureSaver.cpp",
    ],
    hdrs = [
        "include/snapshot/LazySnapshotObj.h",
        "include/snapshot/TextureLoader.h",
        "include/snapshot/TextureSaver.h",
        "include/snapshot/common.h",
        "include/snapshot/interface.h",
    ],
    includes = ["include"],
    copts = [
        "-D_FILE_OFFSET_BITS=64",
        "-Wno-extern-c-compat",
        "-Wno-return-type-c-linkage",
    ],
    defines = ["dfatal=\"(void*)\""],
    deps = [
        "//base:aemu-base-headers",
    ],
)
