# -*- coding: utf-8 -*-
# Copyright 2023 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import logging
import re
import shutil
from pathlib import Path
from typing import Dict, Set, Optional

from aemu.process.runner import check_output, run
from aemu.toolchains.binary_patcher import BinaryPatcher


class PackageConfigPc:
    """
    PackageConfigPc - A class for generating pkg-config (.pc) files.

    This class facilitates the creation of pkg-config files, which are used to provide
    configuration information to build systems and compile/link applications.

    The following things can be shimmed:

    'Requires'    : Set of dependencies you want to specify
    'link_flags'  : Extra link_flags that should be used
    'link_name'   : Create symlink to the existing archive
    'name'        : Shim the name, vs. using the derived one.
    """

    def __init__(
        self,
        name: str,
        version: str,
        release_dir: Path,
        archive: Path,
        includes: Optional[Set[Path]],
        shim: Dict[str, str],
        target: str,
    ) -> None:
        """Initializes a PackageConfigPc object.

        Args:
            name: The name of the package.
            version: The version of the package.
            release_dir: The release directory.
            archive: The path to the archive file.
            includes: A set of include paths.
            shim: A dictionary of shims to apply.
            target: The bazel target.
        """
        self.name = shim.get("name", name)
        self.release_dir = release_dir.as_posix()
        self.version = version
        self.requires = shim.get("Requires", "")
        self.link_flags = shim.get("link_flags", "")
        self.extra_vars = shim.get("extra_vars", {})
        self.archive = archive
        self.target = target
        self.libdir = archive.parent.as_posix()
        if not archive.name:
            if "Libs" not in shim:
                raise KeyError(
                    f"The archive name for {self.name} cannot be derived, so a 'Libs' shim is required"
                )
            self.libs = shim.get("Libs")
            self.lib = self.name
        else:
            self.lib = archive.with_suffix("").name
            if self.archive.suffix == ".a":
                self.libs = f"{self.archive} {self.link_flags}"
            else:
                self.libs = f"-L{self.libdir} -l{self.lib} {self.link_flags}"

        if self.lib.startswith("lib"):
            self.lib = self.lib[3:]
        self.shim = shim

        if includes is None:
            self.include_dir = ""
            self.cflags = ""
        else:
            self.include_dir = next(iter(includes))
            self.cflags = (
                " ".join([f"-I{path.as_posix()}" for path in includes if path.exists()])
                + f" {shim.get('cflags', '')}"
            )

    def is_static(self) -> bool:
        """Returns True if the library is static, False otherwise."""
        return self.archive.suffix == ".a"

    @property
    def extra_args(self) -> str:
        """Returns the extra variables in a format suitable for a .pc file."""
        return "\n".join([f"{k}={v}" for k, v in self.extra_vars.items()])

    def _template(self) -> str:
        """Returns the template for the .pc file."""
        return f"""prefix={self.release_dir}
    includedir={self.include_dir}
    libdir={self.libdir}
    bindir={{prefix}}/bin
    {self.extra_args}
    amc_bazel_target={self.target}
    amc_bin_target={self.archive.absolute().as_posix()}

    Name: {self.name}
    Description: Auto generated by Android Meson Generator
    Version: {self.version}

    Requires: {self.requires}
    Cflags: {self.cflags}
    Libs: {self.libs}
    """

    def _shim_link(self, archive: Path, shim: Dict[str, str]) -> None:
        """
        Create a symbolic link to the library if specified in the shim.

        Args:
            archive (Path): The path to the library archive.
            shim (Dict): The shim configuration.

        Returns:
            None
        """
        if "link_name" in shim and archive.name != shim.get("link_name"):
            logging.info("Shimming link to: %s (%s)", archive, archive.exists())
            shim_link = archive.parent / shim.get("link_name")
            if not shim_link.exists():
                archive.link_to(shim_link)

    def binplace(self, dest_dir: Path) -> None:
        """Binplace the shared libraries to the given location."""
        so_ext = [".so", ".dylib", ".dll"]
        for ext in so_ext:
            for lib in [
                f"lib{self.lib}",
                self.name,
                self.lib,
            ]:
                possible = Path(self.libdir) / f"{lib}{ext}"
                if possible.exists():
                    logging.debug("Binplacing: %s -> %s", possible, dest_dir)
                    destination = dest_dir / f"{lib}{self.shim.get('dll_ext', ext)}"
                    shutil.copyfile(possible, destination)
                    if ext == ".dylib":
                        # Patch up bazel @rpath
                        BinaryPatcher.patch_dylib(destination)
                    if ext == ".so":
                        # Patch up links if needed
                        BinaryPatcher.patch_solib(destination)

                    return

    def write(self, dest_dir: Path) -> None:
        """
        Write the generated pkg-config file to the specified destination directory.

        Args:
            dest_dir (Path): The destination directory.

        Returns:
            None
        """
        dest_dir.mkdir(exist_ok=True)
        location = dest_dir / f"{self.name}.pc"

        # Write the pkg-config file.
        logging.info("Generating %s", location)
        logging.debug(">>> %s", self._template().replace("\n", "\n>>>"))
        with open(location, "w", encoding="utf-8") as f:
            f.write(self._template())
