# Copyright 2025 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//hardware/google/aemu/tools/toolchain/tests/amc/utils:amc_test.bzl", "prepare_build_config")

package(default_visibility = ["//hardware/google/aemu/tools/toolchain/tests/amc:__subpackages__"])

prepare_build_config(
    name = "build_config",
    output = "build-config.jsonc",
    template = "build-config-template.jsonc",
)

exports_files([
    "main.cpp",
    "meson.build",
    "build-config-template.jsonc",
    "shim.jsonc",
    "build_config.h",
])
